# SITE CONFIGURATION
title: Donjon # your site title
author: CharlesLedger 
description: > # Meta description of Homepage
   The whispers from the Donjon of Ledger. The latest news about security research at Ledger.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://donjon.ledger.com/"

# SEO PLUGIN
social:
  name: Ledger Donjon
  links:
    - https://twitter.com/donjonledger
    - https://github.com/ledger-donjon

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Blog', link: '/'}
  - {name: 'Bounty', link: '/bounty'}
  - {name: 'Security Bulletins', link: '/lsb'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
   The security research at Ledger

collections:
  lsb:
    output: true

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: donjon@ledger.fr # email for form submission

twitter_username: donjonledger
github_username:  ledger-donjon


# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
